trigger:
- master
- dev

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

# Initial build will most likely fail on some platforms because noble
# won't build correctly, so don't && it against build/test steps.
- script: |
    yarn
    yarn build && yarn test
  displayName: 'yarn install and build'
  env: { "CI": "true" }
