trigger:
- master
- dev

jobs:
  - job: "MacOS"
    pool:
      vmImage: 'macos-10.13'
    steps:
      - template: 'build/build-test-freeze.yml'
        parameters:
          platform: "macos"
  - job: "Linux"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: 'build/build-test-freeze.yml'
        parameters:
          platform: "linux"
